name: 'Cabal'
description: 'Uses cabal-install to build test benchmark haddock and raaz repository'
author: 'Piyush P Kurur'
steps:
  - name: Information
    run: |
      ghc --version
      cabal --version

  - name: Get the Repository
    uses: actions/checkout@v2

  - name: Cabal Update
    runs: cabal update

  - name: Build
    runs: cabal build

  - name: Test
    runs: cabal test

  - name: Benchmarks
    runs: cabal bench

  - name: Documentation
    runs: cabal haddock

  - name: Raaz information
    run: cabal exec raaz -- info
