name: Building and testing
on: [push, pull_request]
jobs:
  macos:
    name: 'MacOS'
    runs-on: macos-latest
    steps:
      - name: 'Setup'
        uses:./.github/actions/setup-mac
      - name: 'Build and Test'
        uses:./.github/actions/cabal
