name: Building and testing
on: [push, pull_request]
jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ 8.4.4 , 8.6.5, 8.8.1, 8.10.1, head]
    steps:

      - name: 'Enable ppa:hvr/ghc'
        run: |
          sudo add-apt-repository ppa:hvr/ghc -y
          sudo apt-get update -y

      - name: 'Setup'
        run: |
          sudo apt-get install "ghc-$GHCVER" -y
          sudo apt-get install "cabal-install-$CABALVER" -y
          export PATH="/opt/ghc/bin:$PATH"
          export PATH=/opt/cabal/"$CABALVER"/bin:/opt/ghc/"$GHCVER"/bin:$PATH;
        env:
          GHCVER:  ${{ matrix.ghc }}
          CABALVER: 3.0
      - name: Information
        run: |
          echo $PATH
          ghc --version
          cabal --version

      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Submodules
        run: git submodule update --init libverse

      - name: Updating Cabal packages
        run: |
          cabal update

      - name: Build
        run: |
          cabal build
          cabal test
          cabal bench
          cabal haddock

      - name: Raaz information
        run: cabal exec raaz -- info

  macos:
    name: 'MacOS'
    runs-on: macos-latest
    steps:

      - name: 'Setup'
        run: |
          brew update
          brew install ghc cabal-install
          brew info ghc cabal-install

      - name: Information
        run: |
          ghc --version
          cabal --version

      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Submodules
        run: git submodule update --init libverse

      - name: Updating Cabal packages
        run: cabal update

      - name: Build
        run: |
          cabal build
          cabal test
          cabal bench
          cabal haddock

      - name: Raaz information
        run: cabal exec raaz -- info
