name: Building and testing
on: [push, pull_request]
jobs:
  macos:
    name: 'MacOS'
    runs-on: macos-latest
    steps:
      - name: Get the Repository
        uses: actions/checkout@v2
      - name: 'Setup'
        uses: ./.github/actions/setup-mac
      - uses: ./.github/actions/cabal
