name: Checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Repository
        uses: actions/checkout@v2

      - name: 'Trailing white spaces ?'
        uses: harupy/find-trailing-whitespace@master

      - name: 'Set up HLint'
        uses: haskell/actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning
