name: Source Checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Repository
        uses: actions/checkout@v2

      - name: 'Trailing white spaces ?'
        uses: harupy/find-trailing-whitespace@master

      - name: Running hlint
        run: |
          sudo apt-get install curl -y
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
