name: Build
on:
  push:
    branches:
      - master
      - 0.3
  pull_request:
    branches:
      - master
      - 0.3
  schedule:
    # Daily build.
    - cron: '30 8 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: [ '8.4' , '8.6', '8.8', '8.10', '9.0']
        include:
          # - os: ubuntu-latest
          #   ghc: 'latest'
          #   experimental: true
          # - os: ubuntu-latest
          #   ghc: '9.0'
          #   experimental: true
          - os: windows-latest
            ghc: '9.0'
          - os: macos-latest
            ghc: '9.0'

    steps:
      - name: 'Setup'
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Information
        run: |
          ghc --version
          cabal --version

      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Submodules
        run: git submodule update --init libverse

      - name: Updating Cabal packages
        run: |
          cabal update

      - name: Build
        run: |
          cabal build --minimize-conflict-set
          cabal test
          cabal bench
          cabal haddock
          cabal check

      - name: Build with tarball
        if: matrix.os == 'ubuntu-latest'
        run: |
          cabal sdist
          mkdir tarball-build
          mv "dist-newstyle/*.tar.gz tarball-build
          cd tarball-build
          tar xzvf *.tar.gz --strip-components=1
          cabal build
          cabal test
          cabal haddock
          cabal check

      - name: Raaz information
        run: cabal run raaz -- info
