name: Build
on:
  push:
  pull_request:
  schedule:
    # Daily build.
    - cron: '30 8 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ['7.10', '8.0', '8.2', '8.4' , '8.6', '8.8', '8.10', '9.0']
        include:
          # - os: ubuntu-latest
          #   ghc: 'latest'
          #   experimental: true
          # - os: ubuntu-latest
          #   ghc: '9.0'
          #   experimental: true
          - os: windows-latest
            ghc: '9.0'
          - os: macos-latest
            ghc: '9.0'

    steps:
      - name: 'Setup'
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Information
        run: |
          ghc --version
          cabal --version

      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Updating Cabal packages
        run: |
          cabal update

      - name: Build
        run: |
          cabal build --minimize-conflict-set
          cabal test
          cabal bench
          cabal haddock
