name: Source checks
on: [pull_request]
jobs:

  hlint:
    name: Hlint
    runs-on: ubuntu-latest
    steps:

      - name: Installing curl
        run: |
          sudo apt-get install curl -y

      - name: Get the Repository
        uses: actions/checkout@v2

      - name: Running hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
